<?xml version="1.0" encoding="utf-8"?>
<testsuites>
<testsuite name="pytest" errors="0" failures="1" skipped="0" tests="3" time="0.203" timestamp="2021-11-18T10:24:32.521470" hostname="Jaison">
<testcase classname="test_sample" name="test_func" time="0.001" />
<testcase classname="test_sample" name="test_myfunc" time="0.005" />
<testcase classname="test_sample" name="test_fixture" time="0.002">
<failure message="assert 0 == 1&#10;  +0&#10;  -1">
data = [0, 1, 2]

    def test_fixture(data):
&gt;       assert data[0] == 1
E       assert 0 == 1
E         +0
E         -1

test_sample.py:14: AssertionError</failure></testcase></testsuite></testsuites>